// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPFin.Data;

#nullable disable

namespace TPFin.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220722213900_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TPFin.Models.Comentario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPost")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idPost");

                    b.HasIndex("idUser");

                    b.ToTable("Comentario", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            contenido = "Argentina",
                            fecha = new DateTime(2022, 7, 22, 18, 39, 0, 501, DateTimeKind.Local).AddTicks(1905),
                            idPost = 1,
                            idUser = 1
                        },
                        new
                        {
                            id = 2,
                            contenido = "Argentina",
                            fecha = new DateTime(2022, 7, 22, 18, 39, 0, 501, DateTimeKind.Local).AddTicks(1913),
                            idPost = 2,
                            idUser = 2
                        },
                        new
                        {
                            id = 3,
                            contenido = "Argentina",
                            fecha = new DateTime(2022, 7, 22, 18, 39, 0, 501, DateTimeKind.Local).AddTicks(1920),
                            idPost = 3,
                            idUser = 3
                        });
                });

            modelBuilder.Entity("TPFin.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idUser");

                    b.ToTable("Post", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            contenido = "Como estan?",
                            fecha = new DateTime(2022, 7, 22, 18, 39, 0, 501, DateTimeKind.Local).AddTicks(1870),
                            idUser = 1
                        },
                        new
                        {
                            id = 2,
                            contenido = "Todo bien por suerte",
                            fecha = new DateTime(2022, 7, 22, 18, 39, 0, 501, DateTimeKind.Local).AddTicks(1891),
                            idUser = 2
                        },
                        new
                        {
                            id = 3,
                            contenido = "Hola",
                            fecha = new DateTime(2022, 7, 22, 18, 39, 0, 501, DateTimeKind.Local).AddTicks(1898),
                            idUser = 3
                        });
                });

            modelBuilder.Entity("TPFin.Models.PostsTags", b =>
                {
                    b.Property<int>("idPost")
                        .HasColumnType("int");

                    b.Property<int>("idTag")
                        .HasColumnType("int");

                    b.HasKey("idPost", "idTag");

                    b.HasIndex("idTag");

                    b.ToTable("Posts_Tags", (string)null);
                });

            modelBuilder.Entity("TPFin.Models.Reaccion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("idPost")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("tipoReaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idPost");

                    b.HasIndex("idUser");

                    b.ToTable("Reaccion", (string)null);
                });

            modelBuilder.Entity("TPFin.Models.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("palabra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("TPFin.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("isAdm")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "Rojas",
                            bloqueado = false,
                            dni = 111,
                            email = "mariano@mail.com",
                            intentosFallidos = 0,
                            isAdm = true,
                            nombre = "Mariano",
                            password = "111"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Carballal",
                            bloqueado = false,
                            dni = 222,
                            email = "alan@mail.com",
                            intentosFallidos = 0,
                            isAdm = false,
                            nombre = "Alan",
                            password = "222"
                        },
                        new
                        {
                            id = 3,
                            apellido = "Fraga",
                            bloqueado = false,
                            dni = 222,
                            email = "Manuel@mail.com",
                            intentosFallidos = 0,
                            isAdm = false,
                            nombre = "Manuel",
                            password = "333"
                        });
                });

            modelBuilder.Entity("TPFin.Models.UsuarioAmigo", b =>
                {
                    b.Property<int>("idAmigo")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("idAmigo", "idUser");

                    b.HasIndex("idUser");

                    b.ToTable("Usuario_Amigo", (string)null);
                });

            modelBuilder.Entity("TPFin.Models.Comentario", b =>
                {
                    b.HasOne("TPFin.Models.Post", "post")
                        .WithMany("comentarios")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPFin.Models.Usuario", "usuario")
                        .WithMany("misComentarios")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TPFin.Models.Post", b =>
                {
                    b.HasOne("TPFin.Models.Usuario", "user")
                        .WithMany("misPosts")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TPFin.Models.PostsTags", b =>
                {
                    b.HasOne("TPFin.Models.Post", "Post")
                        .WithMany("PostsTags")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPFin.Models.Tag", "Tag")
                        .WithMany("PostsTags")
                        .HasForeignKey("idTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TPFin.Models.Reaccion", b =>
                {
                    b.HasOne("TPFin.Models.Post", "post")
                        .WithMany("reacciones")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPFin.Models.Usuario", "usuario")
                        .WithMany("misReacciones")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TPFin.Models.UsuarioAmigo", b =>
                {
                    b.HasOne("TPFin.Models.Usuario", "user")
                        .WithMany("misAmigos")
                        .HasForeignKey("idAmigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPFin.Models.Usuario", "amigo")
                        .WithMany("amigosMios")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("amigo");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TPFin.Models.Post", b =>
                {
                    b.Navigation("PostsTags");

                    b.Navigation("comentarios");

                    b.Navigation("reacciones");
                });

            modelBuilder.Entity("TPFin.Models.Tag", b =>
                {
                    b.Navigation("PostsTags");
                });

            modelBuilder.Entity("TPFin.Models.Usuario", b =>
                {
                    b.Navigation("amigosMios");

                    b.Navigation("misAmigos");

                    b.Navigation("misComentarios");

                    b.Navigation("misPosts");

                    b.Navigation("misReacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
